AWSTemplateFormatVersion: "2010-09-09"
Description: "This template includes all resources required in the deployment/build of Lucina project."
Parameters:
  Environment: 
    Type: String
Resources:
  DeploymentS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub sjcnet-lucina-deployment-${Environment}
      AccessControl: Private
      LifecycleConfiguration:
        Rules: 
          - 
            ExpirationInDays: 5
            Status: Enabled
      Tags:
        - 
          Key: AppName
          Value: Lucina
        - 
          Key: EnvironmentName
          Value: !Ref Environment